### ISSUE TITLE
16-bit architectures support

### ISSUE THREAD

**Issue by MarcoSpeziali** [andrew-gresyk/FFSM2#49]
`FFSM2` single-header library does not compile on 16-bits architectures.

## Description

`FFSM2` cannot be compiled on a 16-bits architecture because the following code generates a compile-time error:

```cpp
#if INTPTR_MAX == INT64_MAX
    #define FFSM2_ARCHITECTURE_64()    true
    #define FFSM2_ARCHITECTURE_32()    false

    #define FFSM2_64BIT_OR_32BIT(p64, p32)    p64
#elif INTPTR_MAX == INT32_MAX
    #define FFSM2_ARCHITECTURE_64()    false
    #define FFSM2_ARCHITECTURE_32()    true

    #define FFSM2_64BIT_OR_32BIT(p64, p32)    p32
#else
    #error
#endif
```

The case for `INTPTR_MAX == INT16_MAX` is missing.

## Possible Fix

Doing a simple find in the code, neither `FFSM2_64BIT_OR_32BIT` nor `FFSM2_ARCHITECTURE_32/64` defines seems to be used.
Commenting out those defines the code seems to compile just fine. Are they really needed?

## Steps to Reproduce

Unfortunately, the compiler I'm using is not publicly available right now. You could reproduce the error by redefining `INTPTR_MAX` as `INT16_MAX`.

## Environment

* Version used (`clang --version`): `clang version 14.0.4`
* Operating System and version: not relevant

**Comment by andrew-gresyk** [comment]
Thanks for the report.
Removed in `FFSM2_ARCHITECTURE` as you suggested in https://github.com/andrew-gresyk/FFSM2/releases/tag/2.0.3

**Comment by MarcoSpeziali** [comment]
Thanks a lot, it now compiles!

Best Regards,
Marco
